### ISSUE TITLE
TypeError: converter is not a function

### ISSUE THREAD

**Issue by evg1n** [beatgammit/node-coordinator#11]
Sorry this is mistakenly open issue.

**Comment by evg1n** [comment]
Hello @beatgammit,

Awesome package, but I cannot get it to work on [repl.it](https://repl.it/@evg1n/metb3-mortar);

When I console log it returns `undefined`

```
var converter = require('coordinator'),
    fn = converter('latlong', 'mgrs'),
    mgrs = fn(38.897605896, -77.0365219116, 4);

console.log(mgrs);
```

Here is the result:

```
TypeError: converter is not a function
    at /home/runner/metb3-mortar/index.js:3:12
    at Script.runInContext (vm.js:133:20)
    at Object.<anonymous> (/run_dir/interp.js:156:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```
Also it warns user:

```
[typescript]
Could not find a declaration file for module 'coordinator'. '/home/runner/metb3-mortar/node_modules/coordinator/coordinator.js' implicitly has an 'any' type.
  Try `npm install @types/coordinator` if it exists or add a new declaration (.d.ts) file containing `declare module 'coordinator';`
```

You can see the same error on [Runkit](https://runkit.com/evg1n/5e8b8e131dee7600136a48b1)

Keep up the good work, cheers!

**Comment by lorenz068** [comment]
Try to revert to a previous version https://github.com/beatgammit/node-coordinator/issues/8#issuecomment-266175225
